language: node_js
node_js:
  - "4.4.3"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

sudo: false
before_install:
  - npm install -g bower
  - npm install -g gulp
install:
  - npm install
before_script:
  - bower install
  - gulp build
script:
  - ./mvnw test -B
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

