language: node_js
node_js:
  - "4.4.3"
sudo: false
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oraclejdk8
before_install:
  - npm install -g bower
  - npm install -g gulp
  - java -version

install:
  - npm install

before_script:
  - bower install
  - gulp build

script:
  - ./mvnw test -B

after_success:
    # Submit code coverage information to Coveralls
    - coveralls

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.cache/bower
    - $HOME/.npm
    - node_modules
