language: node_js
node_js:
  - "4.4.3"
sudo: required
before_install:
  - npm install -g bower
  - npm install -g gulp
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -l
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - sudo update-java-alternatives -l
  - sudo update-java-alternatives -a
  - sudo update-java-alternatives -l
  - java -version
install:
  - npm install
before_script:
  - bower install
  - gulp build
script:
  - ./mvnw test -B
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

