version: '2'
services:
    klask-postgresql:
        container_name: klask-postgresql
        image: postgres:9.5.2
        volumes:
            - /tmp/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=klask
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
